<a href="https://colab.research.google.com/github/aliakseizvertouski/bet_analyse/blob/main/bet_analyse_draft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/aliakseizvertouski/bet_analyse

Cloning into 'bet_analyse'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 6), reused 7 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (17/17), 4.33 MiB | 11.37 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

bet = pd.read_csv('/content/bet_analyse/bets.csv', sep="|")
events = pd.read_csv('/content/bet_analyse/events.csv')

In [ ]:
bet.head()

,bet_id,player_id,accept_time,create_time,settlement_time,result,amount,payout,profit,bet_type,...,accepted_bet_odd,item_result,event_stage,accepted_odd,item_amount,item_payout,item_profit,event_id,is_free_bet,settlement_status
0,4580f660-d16a-4ad6-8837-47574564a37f,cf928a91-a17d-42cd-8924-7c3fccd54acb,2022-03-14 00:00:00.165,2022-03-13 23:59:54.503,2022-03-14 00:21:59.745,Return,1.00,1.00,0.00,Ordinar,...,7.50,Return,Live,7.50,1.00,1.00,0.00,c3929913-1eef-4703-ada2-fe08fd47c79d,False,Settled
1,7435c382-e448-4c0b-8b56-a9e547ca6605,cf928a91-a17d-42cd-8924-7c3fccd54acb,2022-03-14 00:00:36.819,2022-03-14 00:00:31.160,2022-03-14 00:10:16.243,Win,0.95,2.48,-1.53,Ordinar,...,2.62,Win,Live,2.62,0.95,2.48,-1.53,c3929913-1eef-4703-ada2-fe08fd47c79d,False,Settled
2,ae36ffa2-0bb5-4bd7-8cf6-e15416ae4fc7,f1866879-4b0f-4a58-aaa9-24e6224cb139,2022-03-14 00:01:07.941,2022-03-14 00:01:07.743,2022-03-14 04:37:24.291,Win,3.51,7.51,-4.00,Ordinar,...,2.14,Win,Prematch,2.14,3.51,7.51,-4.00,7b6aaa15-3b2e-4977-8b1a-59472eeb0817,False,Settled
3,57009dc1-60c5-46f7-acb5-1a45a19983b7,e5efcd9c-aa46-48a1-be0e-9e9f9aa37b53,2022-03-14 00:01:27.927,2022-03-14 00:01:27.927,NaN,NaN,1.00,NaN,NaN,Express,...,0.00,NaN,NaN,0.00,0.00,NaN,NaN,0b912707-3b87-4ec3-886c-2b0f96303977,False,Rejected
4,57009dc1-60c5-46f7-acb5-1a45a19983b7,e5efcd9c-aa46-48a1-be0e-9e9f9aa37b53,2022-03-14 00:01:27.927,2022-03-14 00:01:27.927,NaN,NaN,1.00,NaN,NaN,Express,...,0.00,NaN,NaN,0.00,0.00,NaN,NaN,c3929913-1eef-4703-ada2-fe08fd47c79d,False,Rejected

In [ ]:
events.head()

,event_id,sport,category,event
0,101dd0bf-449d-4c8c-b088-db1ef7f3f708,Football,Belgium,Anderlecht U-21 - Royal Antwerp U-21
1,ef534a8d-76f2-482f-bc09-b06a76921dc6,Football,Belgium,KMSK Deinze U-21 - Eupen U-21
2,9443dc96-f46a-447f-895b-1aa970299377,Handball,Russia,Zvezda Zvenihorod (w) - Kuban Krasnodar (w)
3,984ddbe0-e9dc-4cb6-b121-2118c859723e,Ice Hockey,Germany,Straubing Tigers - EHC Red Bull Munchen
4,bbe2dd93-e16e-4834-b5bc-691ed318ddde,Football,South America,General Caballero JLM - Sol de America

# итоги игровых сессий

In [ ]:
# total_turnover = bet["amount"].sum()
# total_profit = bet["profit"].sum()
# total_payout = bet["payout"].sum()

# rtp = total_payout / total_turnover
# ggr = -total_profit

# kpi_table = pd.DataFrame([{
#     "turnover": total_turnover, # ОБОРОТ
#     "profit": total_profit,     # финансовый результат за вычетом ставок
#     "payout": total_payout,     # общая сумма выплат, включая тело ставки
#     "rtp": rtp,                 # Return to Player - коэффициент вывода денег игроками
#     "ggr": ggr                  # Gross Gaming Revenue - прибыль за отчетный период
# }])

# kpi_table

In [ ]:
wins_looses = bet.groupby("result").size().reset_index(name="count")

wins_looses["percent"] = wins_looses["count"] / wins_looses["count"].sum() * 100

wins_looses

# bet1 = bet.groupby('result').agg(

#     total_bets=("bet_id", "count"),
#     percent=("bet_id", "sum"),

# ).reset_index()
# bet1

            result  count    percent
0          Cashout   1285   1.598676
1             Lose  60110  74.783215
2           Return    713   0.887048
3  TechnicalReturn     11   0.013685
4              Win  18260  22.717376

# каково соотношение побед к поражениям?

In [ ]:

win = wins_looses.loc[wins_looses["result"] == "Win", "count"].iloc[0]
cashout = wins_looses.loc[wins_looses["result"] == "Cashout", "count"].iloc[0]
lose = wins_looses.loc[wins_looses["result"] == "Lose", "count"].iloc[0]

print(f"Wins and cashouts: {win+cashout}")
print(f"Lose: {lose}")
print(f"Win/Lose: {win/lose}")

Wins and cashouts: 19545
Lose: 60110
Win/Lose: 0.30377640991515553

# длительность ставок

In [ ]:
sessions = bet

sessions["accept_time"] = pd.to_datetime(bet["accept_time"])
sessions["settlement_time"] = pd.to_datetime(bet["settlement_time"])

sessions['session_duration'] = bet['settlement_time']-bet['accept_time']
sessions = sessions [['bet_id','session_duration']].drop_duplicates()
sessions

                                      bet_id        session_duration
0       4580f660-d16a-4ad6-8837-47574564a37f  0 days 00:21:59.580000
1       7435c382-e448-4c0b-8b56-a9e547ca6605  0 days 00:09:39.424000
2       ae36ffa2-0bb5-4bd7-8cf6-e15416ae4fc7  0 days 04:36:16.350000
3       57009dc1-60c5-46f7-acb5-1a45a19983b7                     NaT
7       bb7ab65b-e84a-4e38-a7e3-6ee611a38fc5  0 days 02:12:30.181000
...                                      ...                     ...
102819  92eeab27-76d1-4bf6-a3f5-bcc46336c526  0 days 00:10:18.006000
102820  6743ab5d-b92b-4fee-b222-3a20629188e2  0 days 00:05:36.016000
102821  16b55410-6495-4bba-a56a-c71250ecfab9  0 days 00:04:07.872000
102822  b5ef6693-659b-4f28-84b4-734072b0f4f0 14 days 07:30:13.167000
102823  131f47e2-7052-4ff0-9ae7-00a18791f6be  1 days 02:18:53.479000

[43801 rows x 2 columns]

# средняя и максимальная длительность ставки

In [ ]:
sessions_mean = sessions['session_duration'].mean()
sessions_max = sessions['session_duration'].max()
print(f"Средняя длительность ставки: {sessions_mean}")
print(f"Максимальная длительность ставки: {sessions_max}")

Средняя длительность ставки: 0 days 02:23:16.694785741
Максимальная длительность ставки: 19 days 01:54:57.980000

In [ ]:
# или можно датафреймом

sessions_mean2 = sessions
sessions_mean2 = sessions_mean2.agg(

    sessions_mean=("session_duration", "mean")

)
sessions_mean2

                       session_duration
sessions_mean 0 days 02:23:16.694785741

# игроки использущие только фриспины

In [ ]:
free_bet_players = (
    bet[['player_id', 'bet_id', 'is_free_bet']]
    .drop_duplicates()
    .groupby(['player_id', 'is_free_bet'])
    .size()
    .unstack(fill_value=0)
    .rename(columns={False: "non_free", True: "free"})
)

free_bet_players = free_bet_players[
    (free_bet_players["non_free"] == 0) &
    (free_bet_players["free"] > 10)
]

free_bet_players

is_free_bet                           non_free  free
player_id
c02e1329-57f6-42af-a478-216c825a9ddc         0    31
f986aad8-d457-482e-aaee-675a37b70b78         0    14

# Customer Churn Analysis (процент халявщиков)

In [ ]:
freeloaders = free_bet_players.reset_index()
freeloaders = freeloaders['player_id'].nunique() / bet['player_id'].nunique() * 100

print (f'итого халявщиков: {freeloaders}')

итого халявщиков: 0.2544529262086514

# а они что-нибудь выигрывают? может жулики?

In [ ]:
# вариант 1 - merge()

profit_by_player = bet.groupby("player_id")["profit"].sum().reset_index()

freeloaders_profit = free_bet_players.merge(profit_by_player, on="player_id", how="left")
freeloaders_profit

                              player_id  non_free  free  profit
0  c02e1329-57f6-42af-a478-216c825a9ddc         0    31     0.0
1  f986aad8-d457-482e-aaee-675a37b70b78         0    14     0.0

In [ ]:
# вариант 2 - ищем данные в одной таблице по значениям из другой таблицы через isin()

profit_by_player = bet.groupby('player_id')['profit'].sum().reset_index()

freeloaders_profit2 = profit_by_player[profit_by_player['player_id'].isin(freeloaders_profit['player_id'])]
freeloaders_profit2

                                player_id  profit
587  c02e1329-57f6-42af-a478-216c825a9ddc     0.0
763  f986aad8-d457-482e-aaee-675a37b70b78     0.0

In [ ]:
# можно поискать кого-то конкретного
persons_profit = profit_by_player[profit_by_player['player_id'] == 'c02e1329-57f6-42af-a478-216c825a9ddc']
persons_profit

                                player_id  profit
587  c02e1329-57f6-42af-a478-216c825a9ddc     0.0

In [ ]:
bet.columns

Index(['bet_id', 'player_id', 'accept_time', 'create_time', 'settlement_time',
       'result', 'amount', 'payout', 'profit', 'bet_type', 'bet_size',
       'accepted_bet_odd', 'item_result', 'event_stage', 'accepted_odd',
       'item_amount', 'item_payout', 'item_profit', 'event_id', 'is_free_bet',
       'settlement_status'],
      dtype='object')

🚀 Самые важные 5 метрик (если коротко)

Если оставить только core:

💰 Player profit (LTV proxy)
🎰 Turnover (amount)
📊 RTP
👤 Active players (DAU/WAU)
🎁 Free-to-paid conversion
💬 Если хочешь дальше

Я могу помочь тебе собрать:

📊
готовый “dashboard pipeline” в pandas
🎯
когортный анализ игроков
📉
churn модель после фриспинов
💰
LTV segmentation (high/medium/low value players)
⚡
risk scoring игроков

Это уже уровень product/data analyst в iGaming

# как часто игроки уходят после поражения? влияет ли на это is_free_bet?